version: '2.1'

services:
  db:
    image: mongo
    ports:
      - "27017"
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      APP_PORT: "${APP_PORT:-8080}"
      DB_URL: "mongodb://db:27017/react-app"
    links:
      - "db"